import { UserProfile, Chat, Message, UserStatus, CallLog } from '../types';

export const MOCK_CURRENT_USER_ID = 'usr_me';

export const MOCK_USERS: UserProfile[] = [
  {
    userId: 'usr_sarah',
    name: 'Sarah Jenkins',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Product Designer & Coffee Aficionado ☕✨',
    email: 'sarah.j@design.io',
    isOnline: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000,
  },
  {
    userId: 'usr_david',
    name: 'David Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Fullstack Architect | React Native Fanatic',
    email: 'david.chen@tech.co',
    isOnline: true,
    lastSeen: Date.now() - 5 * 60 * 1000,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
  {
    userId: 'usr_elena',
    name: 'Elena Rostova',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    bio: 'UI Animations & Motion Design Enthusiast 🎨',
    email: 'elena@motion.studio',
    isOnline: false,
    lastSeen: Date.now() - 42 * 60 * 1000,
    createdAt: Date.now() - 80 * 24 * 60 * 60 * 1000,
  },
  {
    userId: 'usr_marcus',
    name: 'Marcus Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Mobile Security Lead & Crypto Pioneer 🛡️',
    email: 'marcus@cybersec.org',
    isOnline: false,
    lastSeen: Date.now() - 3 * 3600 * 1000,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    userId: 'usr_maya',
    name: 'Maya Lin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Wanderlust & Digital Nomad 🌍📷',
    email: 'maya@nomadlife.io',
    isOnline: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    chatId: 'chat_sarah',
    type: 'direct',
    participants: ['usr_me', 'usr_sarah'],
    participantProfiles: [MOCK_USERS[0]],
    lastMessage: {
      text: 'The glassmorphic design and spring animations look absolutely stunning! 🔥',
      senderId: 'usr_sarah',
      timestamp: Date.now() - 2 * 60 * 1000,
      type: 'text',
    },
    unreadCount: 2,
    bubbleTheme: {
      sentGradient: ['#7C3AED', '#3B82F6'],
      receivedColor: '#1E1E2A',
    },
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 60 * 1000,
  },
  {
    chatId: 'chat_david',
    type: 'direct',
    participants: ['usr_me', 'usr_david'],
    participantProfiles: [MOCK_USERS[1]],
    lastMessage: {
      text: '🎙️ Voice note (0:14)',
      senderId: 'usr_david',
      timestamp: Date.now() - 35 * 60 * 1000,
      type: 'voice',
    },
    unreadCount: 0,
    bubbleTheme: {
      sentGradient: ['#0D9488', '#10B981'],
      receivedColor: '#172727',
    },
    createdAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 35 * 60 * 1000,
  },
  {
    chatId: 'chat_group_core',
    type: 'group',
    groupName: 'Everchat Core Team 🚀',
    groupAvatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    participants: ['usr_me', 'usr_sarah', 'usr_david', 'usr_elena'],
    participantProfiles: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2]],
    lastMessage: {
      text: 'Elena: Shared the new micro-interaction specs for the typing indicator.',
      senderId: 'usr_elena',
      timestamp: Date.now() - 2 * 3600 * 1000,
      type: 'text',
    },
    unreadCount: 0,
    bubbleTheme: {
      sentGradient: ['#EC4899', '#8B5CF6'],
      receivedColor: '#29182C',
    },
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 3600 * 1000,
  },
  {
    chatId: 'chat_elena',
    type: 'direct',
    participants: ['usr_me', 'usr_elena'],
    participantProfiles: [MOCK_USERS[2]],
    lastMessage: {
      text: 'Can you check out this UI motion prototype?',
      senderId: 'usr_me',
      timestamp: Date.now() - 24 * 3600 * 1000,
      type: 'image',
    },
    unreadCount: 0,
    bubbleTheme: {
      sentGradient: ['#F43F5E', '#FB923C'],
      receivedColor: '#2B1A20',
    },
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 24 * 3600 * 1000,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  chat_sarah: [
    {
      id: 'msg_1',
      chatId: 'chat_sarah',
      senderId: 'usr_sarah',
      text: 'Hey Alex! Did you get a chance to check the new MeshX theme specs?',
      type: 'text',
      reactions: {},
      status: 'read',
      createdAt: Date.now() - 25 * 60 * 1000,
    },
    {
      id: 'msg_2',
      chatId: 'chat_sarah',
      senderId: 'usr_me',
      text: 'Yes! The smooth gradients and glassmorphism cards look incredible. Super excited about this release.',
      type: 'text',
      reactions: { usr_sarah: '🔥' },
      status: 'read',
      createdAt: Date.now() - 22 * 60 * 1000,
    },
    {
      id: 'msg_3',
      chatId: 'chat_sarah',
      senderId: 'usr_sarah',
      text: 'Awesome! I uploaded the dark mode bubble themes too. Let me know what you think.',
      type: 'text',
      reactions: {},
      status: 'read',
      createdAt: Date.now() - 15 * 60 * 1000,
    },

    {
      id: 'msg_5',
      chatId: 'chat_sarah',
      senderId: 'usr_sarah',
      text: 'Theme Preview',
      type: 'image',
      mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      reactions: { usr_me: '🔥', usr_sarah: '😍' },
      status: 'read',
      createdAt: Date.now() - 9 * 60 * 1000,
    },
    {
      id: 'msg_6',
      chatId: 'chat_sarah',
      senderId: 'usr_me',
      text: 'That looks like a 10/10 masterwork! The rounded corners and tail radii are spot on.',
      type: 'text',
      replyTo: {
        id: 'msg_5',
        text: 'Theme Preview',
        senderId: 'usr_sarah',
        senderName: 'Sarah Jenkins',
      },
      reactions: {},
      status: 'read',
      createdAt: Date.now() - 5 * 60 * 1000,
    },
    {
      id: 'msg_7',
      chatId: 'chat_sarah',
      senderId: 'usr_sarah',
      text: 'The glassmorphic design and spring animations look absolutely stunning! 🔥',
      type: 'text',
      reactions: {},
      status: 'delivered',
      createdAt: Date.now() - 2 * 60 * 1000,
    },
  ],
  chat_david: [
    {
      id: 'msg_d1',
      chatId: 'chat_david',
      senderId: 'usr_me',
      text: 'Hey David, how is the Firestore live listener performance with Reanimated 3 layout transitions?',
      type: 'text',
      reactions: {},
      status: 'read',
      createdAt: Date.now() - 60 * 60 * 1000,
    },
    {
      id: 'msg_d2',
      chatId: 'chat_david',
      senderId: 'usr_david',
      text: 'Smooth 60fps! Recorded a quick voice summary for you:',
      type: 'text',
      reactions: {},
      status: 'read',
      createdAt: Date.now() - 40 * 60 * 1000,
    },
    {
      id: 'msg_d3',
      chatId: 'chat_david',
      senderId: 'usr_david',
      text: 'Voice Note',
      type: 'voice',
      mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      audioDuration: 14,
      reactions: { usr_me: '👍' },
      status: 'read',
      createdAt: Date.now() - 35 * 60 * 1000,
    },
  ],
};

export const MOCK_STATUSES: UserStatus[] = [
  {
    id: 'st_sarah',
    userId: 'usr_sarah',
    userName: 'Sarah Jenkins',
    userAvatar: MOCK_USERS[0].avatarUrl,
    mediaUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    caption: 'Morning coffee & UI component tweaking ⚡☕',
    createdAt: Date.now() - 2 * 3600 * 1000,
    expiresAt: Date.now() + 22 * 3600 * 1000,
    viewedBy: [],
  },
  {
    id: 'st_maya',
    userId: 'usr_maya',
    userName: 'Maya Lin',
    userAvatar: MOCK_USERS[4].avatarUrl,
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    caption: 'Sunset vibes from Bali 🌅🌊',
    createdAt: Date.now() - 5 * 3600 * 1000,
    expiresAt: Date.now() + 19 * 3600 * 1000,
    viewedBy: ['usr_me'],
  },
  {
    id: 'st_david',
    userId: 'usr_david',
    userName: 'David Chen',
    userAvatar: MOCK_USERS[1].avatarUrl,
    mediaUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    caption: 'Everchat build compiling cleanly! 🎉',
    createdAt: Date.now() - 8 * 3600 * 1000,
    expiresAt: Date.now() + 16 * 3600 * 1000,
    viewedBy: ['usr_me'],
  },
];

export const MOCK_CALLS: CallLog[] = [
  {
    id: 'call_1',
    callerId: 'usr_sarah',
    callerName: 'Sarah Jenkins',
    callerAvatar: MOCK_USERS[0].avatarUrl,
    receiverId: 'usr_me',
    receiverName: 'Alex Vance',
    receiverAvatar: '',
    type: 'video',
    status: 'connected',
    duration: 342,
    timestamp: Date.now() - 3 * 3600 * 1000,
  },
  {
    id: 'call_2',
    callerId: 'usr_david',
    callerName: 'David Chen',
    callerAvatar: MOCK_USERS[1].avatarUrl,
    receiverId: 'usr_me',
    receiverName: 'Alex Vance',
    receiverAvatar: '',
    type: 'voice',
    status: 'missed',
    duration: 0,
    timestamp: Date.now() - 24 * 3600 * 1000,
  },
  {
    id: 'call_3',
    callerId: 'usr_me',
    callerName: 'Alex Vance',
    callerAvatar: '',
    receiverId: 'usr_elena',
    receiverName: 'Elena Rostova',
    receiverAvatar: MOCK_USERS[2].avatarUrl,
    type: 'voice',
    status: 'connected',
    duration: 185,
    timestamp: Date.now() - 48 * 3600 * 1000,
  },
];
